### ISSUE TITLE
Gin example?

### ISSUE THREAD

**Issue by akestner** [rs/cors#22]
Any chance we could get an example integration for [Gin](https://github.com/gin-gonic/gin)?

**Comment by ADone** [comment]
@akestner I had added a Gin support into my fork of cors package.
I can create PR for this feature if anyone is interested in it
For example:
```go
api := gin.Default()
api.Use(cors.New(cors.Options{
	AllowedOrigins:     []string{"*"},
	AllowedMethods:     []string{"GET", "OPTIONS", "POST", "DELETE"},
	AllowedHeaders:     []string{"Authorization", "Accept"},
	AllowCredentials:   true,
	OptionsPassthrough: false,
	Debug:              true,
}).Gin())
```
But it brings a gin package as dependency because all main functionality is private at cors package and cannot be extracted easily for separated gin-cors package

**Comment by rs** [comment]
Sure, send a PR, I will merge it. Thx
